export {default as Welcome} from 'containers/Welcome';
export {default as Main} from 'containers/Main';
export {default as Device} from 'containers/Device';
export {default as DeviceWork} from 'containers/DeviceWork';
export {default as NotFound} from 'containers/NotFound';
export {default as OAuth2RedirectHandler} from 'containers/OAuth2RedirectHandler';
export {default as TestWork} from 'containers/TestWork';
export {default as HubAdmin} from 'containers/HubAdmin';
export {default as DataModelerWork} from 'containers/DataModelerWork';